version: '3.8'

services:
  # Serviço de banco de dados PostgreSQL
  postgres:
    image: postgres:14
    container_name: apconsult-postgres
    restart: always
    environment:
      POSTGRES_USER: apconsult
      POSTGRES_PASSWORD: ${DB_PASSWORD:-apconsult123}
      POSTGRES_DB: apconsult_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - apconsult-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apconsult"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço de API backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apconsult-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: apconsult
      DB_PASSWORD: ${DB_PASSWORD:-apconsult123}
      DB_NAME: apconsult_manager
      JWT_SECRET: ${JWT_SECRET:-APConsultSecretKey123456789012345678901}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-APConsultSecretKey123456789012345678901}
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - apconsult-network
    volumes:
      - ./logs:/app/logs

  # Serviço de frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apconsult-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - apconsult-network

  # Serviço RustDesk HBBS (ID/Relay Server)
  rustdesk-hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    restart: always
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21118:21118"
    command: hbbs -r api.apconsult.com.br
    volumes:
      - rustdesk_data:/root
    networks:
      - apconsult-network

  # Serviço RustDesk HBBR (Relay Server)
  rustdesk-hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    restart: always
    ports:
      - "21117:21117"
      - "21119:21119"
    command: hbbr -r api.apconsult.com.br
    depends_on:
      - rustdesk-hbbs
    volumes:
      - rustdesk_data:/root
    networks:
      - apconsult-network

volumes:
  postgres_data:
  rustdesk_data:

networks:
  apconsult-network:
    driver: bridge 